# Generated by Django 3.2.7 on 2023-01-30 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='s_school',
            new_name='s_branch',
        ),
    ]
